config:
    resource: "@ConfigBundle/Resources/config/routing.yml"
    prefix:   /

banco:
    resource: "@BancoBundle/Resources/config/routing.yml"
    prefix:   /

notificaciones:
    resource: "@NotificacionesBundle/Resources/config/routing.yml"
    prefix:   /
incidencias:
    resource: "@IncidenciasBundle/Resources/config/routing.yml"
    prefix:   /

inventario:
    resource: "@InventarioBundle/Resources/config/routing.yml"
    prefix:   /

finanzas:
    resource: "@FinanzasBundle/Resources/config/routing.yml"
    prefix:   /

empresa:
    resource: "@EmpresaBundle/Resources/config/routing.yml"
    prefix:   /

documentos:
    resource: "@DocumentosBundle/Resources/config/routing.yml"
    prefix:   /

home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /

rrhh:
    resource: "@RrhhBundle/Resources/config/routing.yml"
    prefix:   /

login:
    resource: "@LoginBundle/Resources/config/routing.yml"
    prefix:   /

#backend:
#    resource: "@BackendBundle/Resources/config/routing.yml"
#    prefix:   /

app:
    resource: "@LoginBundle/Controller/"
    type:     annotation
