# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        BackendBundle\Entity\Usuario:
            algorithm: bcrypt
            cost: 4 

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
       user_db_provider:
           entity:
               class: BackendBundle:Usuario
               property: username
               
 
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: user_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: logout
                target: /
                   
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/, roles: IS_AUTHENTICATED_ANONIMOUSLY }
        - { path: ^/home, roles: [ROLE_USER, ROLE_ADMIN ] }
        - { path: ^/finanzas, roles: [ROLE_USER, ROLE_ADMIN ] }
        - { path: ^/inventario, roles: [ROLE_USER, ROLE_ADMIN ] }
        - { path: ^/config, roles: [ROLE_USER, ROLE_ADMIN ] }
        - { path: ^/incidenias, roles: [ROLE_USER, ROLE_ADMIN ] }
        - { path: ^/notificaciones, roles: [ROLE_USER, ROLE_ADMIN  ] }
        - { path: ^/banco, roles: [ROLE_USER, ROLE_ADMIN ] }
        - { path: ^/facturas, roles: [ROLE_USER, ROLE_ADMIN ] }
        - { path: ^/departamentos, roles: [ROLE_USER, ROLE_ADMIN ] }
        - { path: ^/rrhh, roles: [ROLE_USER, ROLE_ADMIN ] }
        - { path: ^/usuario, roles: [ROLE_USER, ROLE_ADMIN ] }
        - { path: ^/movimientosbanco, roles: [ROLE_USER, ROLE_ADMIN ] }
        - { path: ^/proveedores-cliente, roles: [ROLE_USER, ROLE_ADMIN ] }
        - { path: ^/oc-op, roles: [ROLE_USER, ROLE_ADMIN ] }
        - { path: ^/banco, roles: [ROLE_USER, ROLE_ADMIN ] }
        - { path: ^/campana, roles: [ROLE_USER, ROLE_ADMIN ] }
        