backend_proveedoresclientes:
    resource: "@FinanzasBundle/Resources/config/routing/proveedoresclientes.yml"
    prefix:   /
backend_contactos:
    resource: "@FinanzasBundle/Resources/config/routing/contactos.yml"
    prefix:   /
backend_oc:
    resource: "@FinanzasBundle/Resources/config/routing/ordenescompra.yml"
    prefix:   /oc-op
backend_itemsoc:
    resource: "@FinanzasBundle/Resources/config/routing/itemsoc.yml"
    prefix:   /oc-op/items
backend_autorizaciones:
    resource: "@FinanzasBundle/Resources/config/routing/autorizaciones.yml"
    prefix:   /autorizaciones
